### ISSUE TITLE
Trajectory visualization  cg to aa ?

### ISSUE THREAD

**Issue by aashuph16221** [ksy141/mstool#3]
Hello,

Does MSTool have any options for visualizing the CG to all-atom trajectory?

Regards

**Comment by ksy141** [comment]
Hi,Sorry but no. Mstool does not have an internal visualization function. You can use either VMD, Pymol, or ChimeraX.Best,SiyoungOn Oct 19, 2024, at 9:50 PM, aashuph16221 ***@***.***> wrote:﻿
Hello,
Does MSTool have any options for visualizing the CG to all-atom trajectory?
Regards
