### ISSUE TITLE
Example files for cyclohexane

### ISSUE THREAD

**Issue by amarkrishna47** [ksy141/mstool#5]
Hi!

Was trying out examples provided with mstool. Would it be possible to access the cyclohexane test case, which was explained in the publication?

Thanks,
Amar

**Comment by ksy141** [comment]
Hi Amar,

Here are the input files:

$ cat cg.pdb
ATOM      1 ONE  CYHEA   1     -15.000 -15.000 -15.000  0.00  0.00

$ cat mapping.dat
RESI CYHE
[ ONE ]
C1 H1A H1B
C2 H2A H2B
C3 H3A H3B
C4 H4A H4B
C5 H5A H5B
C6 H6A H6B

[ dihedral ]
; chair
C1 C2 C3 C4 56.15
C4 C5 C6 C1 -56.15

$ cat ff.xml
<ForceField>
  <Residues>
    <Residue name="CYHE">
      <Atom charge="-0.18" name="C1"  type="CG321"/>
      <Atom charge="+0.09" name="H1A" type="HGA2"/>
      <Atom charge="+0.09" name="H1B" type="HGA2"/>
      <Atom charge="-0.18" name="C2"  type="CG321"/>
      <Atom charge="+0.09" name="H2A" type="HGA2"/>
      <Atom charge="+0.09" name="H2B" type="HGA2"/>
      <Atom charge="-0.18" name="C3"  type="CG321"/>
      <Atom charge="+0.09" name="H3A" type="HGA2"/>
      <Atom charge="+0.09" name="H3B" type="HGA2"/>
      <Atom charge="-0.18" name="C4"  type="CG321"/>
      <Atom charge="+0.09" name="H4A" type="HGA2"/>
      <Atom charge="+0.09" name="H4B" type="HGA2"/>
      <Atom charge="-0.18" name="C5"  type="CG321"/>
      <Atom charge="+0.09" name="H5A" type="HGA2"/>
      <Atom charge="+0.09" name="H5B" type="HGA2"/>
      <Atom charge="-0.18" name="C6"  type="CG321"/>
      <Atom charge="+0.09" name="H6A" type="HGA2"/>
      <Atom charge="+0.09" name="H6B" type="HGA2"/>
      <Bond atomName1="C1" atomName2="H1A"/>
      <Bond atomName1="C1" atomName2="H1B"/>
      <Bond atomName1="C2" atomName2="H2A"/>
      <Bond atomName1="C2" atomName2="H2B"/>
      <Bond atomName1="C3" atomName2="H3A"/>
      <Bond atomName1="C3" atomName2="H3B"/>
      <Bond atomName1="C4" atomName2="H4A"/>
      <Bond atomName1="C4" atomName2="H4B"/>
      <Bond atomName1="C5" atomName2="H5A"/>
      <Bond atomName1="C5" atomName2="H5B"/>
      <Bond atomName1="C6" atomName2="H6A"/>
      <Bond atomName1="C6" atomName2="H6B"/>
      <Bond atomName1="C1" atomName2="C2"/>
      <Bond atomName1="C2" atomName2="C3"/>
      <Bond atomName1="C3" atomName2="C4"/>
      <Bond atomName1="C4" atomName2="C5"/>
      <Bond atomName1="C5" atomName2="C6"/>
      <Bond atomName1="C6" atomName2="C1"/>
    </Residue>
  </Residues>
</ForceField>

You can backmap a cyclohexane molecule with the above input files:
mstool.Ungroup('cg.pdb', 'aa.pdb', mapping='mapping.dat’)
mstool.REM('aa.pdb', 'aa_final.pdb', mapping='mapping.dat', ff_add='ff.xml', pbc=False)
mstool.CheckStructure('aa_final.pdb', mapping='mapping.dat’)

Please let me know if it works.
Best,
Siyoung

**Comment by amarkrishna47** [comment]
Hi Siyoung,

Thanks for sharing the data. It works well.
Great job on the back mapping tool! It's very user-friendly.

Regards,
Amar
